protocol = "gpio-digital-output"
doc = """
Daemon to control one gpio pin as a digital output.
"""
traits = ["is-discrete", "is-daemon"]
hardware = ["raspberry-pi:4b", "raspberry-pi:3b+"]

[links]
source = "https://gitlab.com/yaq/yaqd-rpi-gpio/"
bugtracker = "https://gitlab.com/yaq/yaqd-rpi-gpio/-/issues/"
manufacturer = "https://www.raspberrypi.org/"

[installation]
PyPI = "https://pypi.org/project/yaqd-rpi-gpio/"

[config.index]
type = "int"
doc = "Pin to control. Use Broadcom SOC channel index, NOT board pins."

[config.watchdog_timeout]
type = ["null", "int"]
doc = "Watchdog timeout, in seconds. Watchdog is fed each time position is set. If watchdog times out, destination is set to watchdog_timeout_destination (default zero)"
default = "__null__"

[config.watchdog_timeout_destination]
type = "float"
doc = "Destination set if watchdog timer times out."
default = 0.0

[config.pwm_frequency]
type = "float"
doc = "Pulse width modulation frequency, in Hz."
default = 5.0