[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "yaqd_rpi_gpio"
dist-name = "yaqd-rpi-gpio"
author = "Blaise Thompson"
author-email = "blaise@untzag.com"
home-page = "https://yaq.fyi"
description-file = "README.md"
requires-python = ">=3.7"
requires = ["yaqd-core>=2021.3.0", "gpiozero"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Scientific/Engineering",
]

[tool.flit.metadata.urls]
Source = "https://gitlab.com/yaq/yaqd-rpi-gpio"
Issues = "https://gitlab.com/yaq/yaqd-rpi-gpio/-/issues"

[tool.flit.metadata.requires-extra]
dev = ["black", "pre-commit"]

[tool.flit.scripts]
yaqd-gpio-pwm-output = "yaqd_rpi_gpio._gpio_pwm_output:GpioPwmOutput.main"
yaqd-gpio-digital-output = "yaqd_rpi_gpio._gpio_digital_output:GpioDigitalOutput.main"
yaqd-gpio-digital-sensor = "yaqd_rpi_gpio._gpio_digital_sensor:GpioDigitalSensor.main"

[tool.black]
line-length = 99
target-version = ['py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''
